### ISSUE TITLE
cannot import name '_normalize_score_results' from 'sklearn.model_selection._validation'

### ISSUE THREAD

**Issue by ghost** [Yard1/hpbandster-sklearn#1]
![image](https://user-images.githubusercontent.com/28674274/103320517-3ae3e480-4a68-11eb-9383-d719ff0e0e84.png)

any idea about this?

**Comment by Yard1** [comment]
What sklearn version are you using? 1.1.0 works only with sklearn 0.23. If you are using sklearn 0.24, you need to install version 2.0.0

Also, now I see that I forgot to update the version number in `__init__`. My bad.

**Comment by ghost** [comment]
thank you for your response. it works
