### ISSUE TITLE
Request: remove print statements from SklearnWorker

### ISSUE THREAD

**Issue by arainboldt** [Yard1/hpbandster-sklearn#3]
Great implementation! 

It would be nice if the below print statements were removed.

[https://github.com/Yard1/hpbandster-sklearn/blob/master/hpbandster_sklearn/SklearnWorker.py#L644](url)

[https://github.com/Yard1/hpbandster-sklearn/blob/master/hpbandster_sklearn/HpBandSterSearchCV.py#L392](url)

**Comment by Yard1** [comment]
Thanks, I must have left them there by mistake. Will deal with it!
